// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-5ZvGfyenrQklPqN2Qso22bIg728SBrI',
    appId: '1:241701896458:web:dfd9c6eaa6e0b78d29baf3',
    messagingSenderId: '241701896458',
    projectId: 'task-app-9ee14',
    authDomain: 'task-app-9ee14.firebaseapp.com',
    storageBucket: 'task-app-9ee14.appspot.com',
    measurementId: 'G-QJSE325W9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLwiPqTzYVuAzRKMQS9_zqyEN2XSuJQVI',
    appId: '1:241701896458:android:dc67bbd10dbc065329baf3',
    messagingSenderId: '241701896458',
    projectId: 'task-app-9ee14',
    storageBucket: 'task-app-9ee14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-sx5WkX3aH7FhAolvmU2e4gqTe9OSL6k',
    appId: '1:241701896458:ios:2991e864b88caa3029baf3',
    messagingSenderId: '241701896458',
    projectId: 'task-app-9ee14',
    storageBucket: 'task-app-9ee14.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-sx5WkX3aH7FhAolvmU2e4gqTe9OSL6k',
    appId: '1:241701896458:ios:2991e864b88caa3029baf3',
    messagingSenderId: '241701896458',
    projectId: 'task-app-9ee14',
    storageBucket: 'task-app-9ee14.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-5ZvGfyenrQklPqN2Qso22bIg728SBrI',
    appId: '1:241701896458:web:fc9b185ce541fb8429baf3',
    messagingSenderId: '241701896458',
    projectId: 'task-app-9ee14',
    authDomain: 'task-app-9ee14.firebaseapp.com',
    storageBucket: 'task-app-9ee14.appspot.com',
    measurementId: 'G-G55S06ZJW5',
  );
}
